In [ ]:
#Checking for the version of Python and NumPy  installed
import numpy as np
import sys
print("Installed Python version is  : {0} ".format(sys.version))
print("Installed NumPy version is   : {0} ".format(np.__version__))

Installed Python version is  : 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] 
Installed NumPy version is   : 1.23.5 


##1. **np.array(arr, dtype=None, copy=True, order='K', subok=False, ndmin=0):**
## Creating NumPy Array from Python List or Tuple or Iterable
   - Creates a NumPy array from a list or iterable `arr`.
   - Use when you have data in a Python list or similar structure that you want to convert to a NumPy array.

In [ ]:
# Creating NumPy array from Python List
import numpy as np
num_list = [1,2,3,4,5]
num_array = np.array(num_list)
print(num_array)
print(type(num_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# Creating NumPy array from Python tuple
import numpy as np
num_tuple = (1,2,3,4,5)
num_array = np.array(num_tuple)
print(num_array)
print(type(num_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# 2-dimensional array from Python List
import numpy as np
num_list = [[1,2,3],[4,5,6]]
num_array = np.array(num_list)
print(num_array)
print(type(num_array))


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


##2. **np.empty(shape, dtype=float, order='C'):**
   - Creates an uninitialized array with the given shape.
   - Use when you need an array quickly for data storage but don't require specific initial values.

In [ ]:
# creating NumPy array from usning np.empty
import numpy as np
num_array = np.empty((2,3)) #2 rows and 3 columns
print(num_array) #empty array
print(type(num_array))


[[4.76237835e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 5.82634115e+303 5.45942539e-321]]
<class 'numpy.ndarray'>


## **3. np.empty_like(prototype, dtype=None, order='K', subok=True, shape=None):**
   - Creates a new array with the same shape and data type as the `prototype`.
   - Use when you want an empty array with the same properties as an existing array.

The np.empty_like() function in NumPy is used to create a new NumPy array with the same shape and data type as an existing array or array-like object. However, unlike np.empty(), it doesn't initialize the elements of the new array, leaving them with arbitrary values (possibly whatever was already in that memory location).

In [ ]:
#Example:1 Creating NumPy array from using np.empty_like()
import numpy as np
num_array = np.array([[2,0],[1,2]])
arr_empty_like = np.empty_like(num_array)

print("initial array:\n",num_array)
print("data type of initial array :\n",num_array.dtype)
print("shape of initial array :\n",num_array.shape)

print("arr_empty_like: \n",arr_empty_like)
print("data type of arr_empty_like: \n",arr_empty_like.dtype)
print("shape of arr_empty_like: \n",arr_empty_like.shape)

initial array:
 [[2 0]
 [1 2]]
data type of initial array :
 int64
shape of initial array :
 (2, 2)
arr_empty_like: 
 [[100665250702616               0]
 [              0               0]]
data type of arr_empty_like: 
 int64
shape of arr_empty_like: 
 (2, 2)


In [ ]:
#Example:2 Creating NumPy array from using np.empty_like() with arry_like object
import numpy as np
arr_like = ([ [1,1],[1,2]])  # array_like
num_array1 = np.empty_like(arr_like)
print(num_array1)
print(type(num_array1))

[[2 0]
 [1 2]]
<class 'numpy.ndarray'>


## **Creating arrays which are filled with constant values.**

### **4. np.zeros(shape, dtype=None, order='C'):**
   - Creates an array filled with zeros.
   - Use when you need an array with all elements set to 0.

In [ ]:
#Creating NumPy array from using np.zeros()
import numpy as np
arr_with_zeros = np.zeros((2,3))
print(arr_with_zeros)
print(type(arr_with_zeros))

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


### **5. np.zeros_like(prototype, dtype=None, order='K', subok=True, shape=None):**
   - Creates a new array with the same shape and data type as the `prototype`, filled with zeros.
   - Use when you want an array with the same properties as an existing array but filled with zeros.

In [ ]:
#Creating NumPy array from using np.zeros_like()
import numpy as np
num_array = np.array([[1,2],[3,4]])
arr_zero_like = np.zeros_like(num_array)

print("initial array:\n",num_array)
print("data type of initial array :\n",num_array.dtype)
print("shape of initial array :\n",num_array.shape)

print("arr_zero_like: \n",arr_zero_like)
print("data type of arr_zero_like: \n",arr_zero_like.dtype)
print("shape of arr_zero_like: \n",arr_zero_like.shape)

initial array:
 [[1 2]
 [3 4]]
data type of initial array :
 int64
shape of initial array :
 (2, 2)
arr_zero_like: 
 [[0 0]
 [0 0]]
data type of arr_zero_like: 
 int64
shape of arr_zero_like: 
 (2, 2)


### **6. np.ones(shape, dtype=None, order='C'):**
   - Creates an array filled with ones.
   - Use when you need an array with all elements set to 1.

In [ ]:
#Creating NumPy array from using np.ones()
import numpy as np
arr_with_ones = np.ones((2,3))
print(arr_with_ones)
print(type(arr_with_ones))

[[1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>


In [ ]:
# creating 1-dimensional NumPy array from using np.zeros()
import numpy as np
arr_zeros_1d = np.zeros(3)
print(arr_zeros_1d)
print(type(arr_zeros_1d))


[0. 0. 0.]
<class 'numpy.ndarray'>


In [ ]:
# creating 1-dimensional NumPy array from using np.ones()
import numpy as np
arr_ones_1d = np.ones(3)
print(arr_ones_1d)
print(type(arr_ones_1d))


[1. 1. 1.]
<class 'numpy.ndarray'>


### **7. np.ones_like(prototype, dtype=None, order='K', subok=True, shape=None):**
   - Creates a new array with the same shape and data type as the `prototype`, filled with ones.
   - Use when you want an array with the same properties as an existing array but filled with ones.

In [ ]:
#Creating NumPy array from using np.ones_like()
import numpy as np
num_array = np.array([[1,2],[3,4]])
arr_ones_like = np.ones_like(num_array)

#printing initial array and its shape and data type
print("initial array:\n",num_array)
print("data type of initial array :\n",num_array.dtype)
print("shape of initial array :\n",num_array.shape)

#printing ones_like array and its shape and data type
print("arr_ones_like: \n",arr_ones_like)
print("data type of arr_ones_like: \n",arr_ones_like.dtype)
print("shape of arr_ones_like: \n",arr_ones_like.shape)


initial array:
 [[1 2]
 [3 4]]
data type of initial array :
 int64
shape of initial array :
 (2, 2)
arr_ones_like: 
 [[1 1]
 [1 1]]
data type of arr_ones_like: 
 int64
shape of arr_ones_like: 
 (2, 2)


### **8. np.full(shape, fill_value, dtype=None, order='C'):**
  - Creates an array filled with a specified value.
  - Use when you need an array with all elements set to a specific value.

In [ ]:
#Creating NumPy array from using np.full()
import numpy as np
arr_full = np.full((2,3),5)
print(arr_full)
print(type(arr_full))

[[5 5 5]
 [5 5 5]]
<class 'numpy.ndarray'>


#### **11. np.full_like(prototype, fill_value, dtype=None, order='K', subok=True, shape=None):**
  - Creates a new array with the same shape and data type as the `prototype`, filled with a specified value.
  - Use when you want an array with the same properties as an existing array but filled with a specific value.

In [ ]:
#Creating NumPy array from using np.full_like()
import numpy as np
arr_ones= np.ones((2,3))
arr_full_like = np.full_like(arr_ones,5)

#printing initial array and its shape and data type
print("initial array:\n",arr_ones)
print("data type of initial array :\n",arr_ones.dtype)
print("shape of initial array :\n",arr_ones.shape)

#printing ones_like array and its shape and data type
print("arr_ones_like: \n",arr_full_like)
print("data type of arr_ones_like: \n",arr_full_like.dtype)
print("shape of arr_ones_like: \n",arr_full_like.shape)

initial array:
 [[1. 1. 1.]
 [1. 1. 1.]]
data type of initial array :
 float64
shape of initial array :
 (2, 3)
arr_ones_like: 
 [[5. 5. 5.]
 [5. 5. 5.]]
data type of arr_ones_like: 
 float64
shape of arr_ones_like: 
 (2, 3)


## **Creating Arrays populated with a Range.**

## np.arange():

In [ ]:
#Example#1:Creating NumPy array from using np.arange()
import numpy as np
arr_arange = np.arange(10)
print(arr_arange)
print(type(arr_arange))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
#Example#2:Creating NumPy array from using np.arange() with start, stop and step
import numpy as np
arr_arange = np.arange(1,10,2) # here 1 is start, 10 is stop and 2 is step
print(arr_arange)
print(type(arr_arange))

[1 3 5 7 9]
<class 'numpy.ndarray'>


## np.linspace():

In [ ]:
#Example#3:Creating NumPy array from using np.linspace()
import numpy as np
#here 1 is start, 10 is stop and 4 is number of elements
arr_linspace = np.linspace(1,10,4)
print(arr_linspace)
print(type(arr_linspace))

[ 1.  4.  7. 10.]
<class 'numpy.ndarray'>


## **Creating Arrays Filled with Logarithmic Sequences**
### **np.logspace():**

In [ ]:
#Creating NumPy array from using np.logspace()
import numpy as np

arr_logspace = np.logspace(1,2,11)
print(arr_logspace)
print(type(arr_logspace))

[ 10.          12.58925412  15.84893192  19.95262315  25.11886432
  31.6227766   39.81071706  50.11872336  63.09573445  79.43282347
 100.        ]
<class 'numpy.ndarray'>


## **Creating Arrays with random values**

### **using np.random.random() and np.rand.rand()**

In [ ]:
#Generating a single random number
import numpy as np

random_number1 = np.random.random()
print("Random number using np.random.random() : ",random_number1)
print(type(random_number1))

random_number2 = np.random.rand()
print("Random number using np.random.rand() : ",random_number2)
print(type(random_number2))



Random number using np.random.random() :  0.7805291762864555
<class 'float'>
Random number using np.random.rand() :  0.11827442586893322
<class 'float'>


In [ ]:
# Creating NumPy Array with random values with specified shape
import numpy as np
#using np.random.random()
arr_random1 = np.random.random((2,3))
print("Array with random values using np.random.random() : \n",arr_random1)
print(type(arr_random1))

##using np.random.rand()
arr_random2 = np.random.rand(2,3)
print("\nArray with random values using np.random.rand() :\n ",arr_random2)
print(type(arr_random2))

Array with random values using np.random.random() : 
 [[0.6235637  0.38438171 0.29753461]
 [0.05671298 0.27265629 0.47766512]]
<class 'numpy.ndarray'>

Array with random values using np.random.rand() :
  [[0.81216873 0.47997717 0.3927848 ]
 [0.83607876 0.33739616 0.64817187]]
<class 'numpy.ndarray'>


### using **np.random.seed()** to set the random seed so that we get the same random numbers every time

In [ ]:
# Using np.random.seed()
import numpy as np
np.random.seed(0)
arr_random = np.random.rand(2,3)
print(arr_random)
print(type(arr_random))

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]]
<class 'numpy.ndarray'>


## **np.random.randn()**

In [ ]:
#Using np.random.randn()
import numpy as np
np.random.seed(0)

arr_random = np.random.randn(2,3)
print(arr_random)
print(type(arr_random))

[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]]
<class 'numpy.ndarray'>


## **np.random.randint()**

In [ ]:
# Using np.random.randint()
import numpy as np
np.random.seed(0)

# here 0 is start, 10 is stop and (2,3) is shape
arr_random = np.random.randint(0,10,(2,3))

print(arr_random)
print(type(arr_random))


[[5 0 3]
 [3 7 9]]
<class 'numpy.ndarray'>


## **Attributes of a NumPy Array.**

In [ ]:
#Basic attributes of NumPy array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print("Initial array :\n",arr)
print("Shape of array : ",arr.shape)
print("num of dimensions : ",arr.ndim)
print("Size of array : ",arr.size)
print("Datatype of array : ",arr.dtype)
print("Itemsize of array : ",arr.itemsize)
print("Nbytes of array : ",arr.nbytes)

Initial array :
 [[1 2 3]
 [4 5 6]]
num of dimensions :  2
Shape of array :  (2, 3)
Size of array :  6
Datatype of array :  int64
Itemsize of array :  8
Nbytes of array :  48
