## **Martix and vector Products**

### **Dot Product (np.dot())**

In [ ]:
#Example#1 np.dot() with 2D arrays (dot product of two matrices)
import numpy as np

a = np.array([[10, 20], [30, 40]])
b = np.array([[50, 60], [70, 80]])

print("Matrix product of a and b:\n",np.dot(a, b))

#Example#2 np.dot() with 1D arrays (dot product of two vectors)
import numpy as np

q = np.array([10, 60, 30])
p = np.array([520, 741, 808])

print("Vector product of q and p:\n",np.dot(q, p))


Matrix product of a and b:
 [[1900 2200]
 [4300 5000]]
Vector product of q and p:
 73900


### **Matrix Multiplication (np.matmul() or @)**

In [ ]:
# matrix multiplication usig np.matmul()
import numpy as np

a = np.array([[10, 20], [30, 40]])
b = np.array([[50, 60], [70, 80]])

print("Matrix product of a and b using np.matmul() function:\n",np.matmul(a, b))
print("Matrix product of a and b using @ operator:\n",a @ b)


Matrix product of a and b using np.matmul() function:
 [[1900 2200]
 [4300 5000]]
Matrix product of a and b using @ operator:
 [[1900 2200]
 [4300 5000]]


### **Dot Product of Vectors (np.vdot())**

In [ ]:
#Example#1: dot product of two vectors using np.vdot()
import numpy as np
r = np.array([10, 60, 30])
s = np.array([520, 741, 808])
print("Vector product of r and s vectors:\n",np.vdot(r, s))

#Example#2: dot product of two matrices using np.vdot()
import numpy as np
r = np.array([[10, 20], [30, 40]])
s = np.array([[50, 60], [70, 80]])
print("Vector product of r and s matrix:\n",np.vdot(r, s))

#Example#3: dot product of two matrices with complex numbers using np.vdot()
import numpy as np
r = np.array([10+20j,30+40j])
s = np.array([50+60j,70+80j])
print("Vector product of r and s matrix with complex numbers:\n",np.vdot(r, s))
print("Vector product of r and s matrix with complex numbers:\n",np.vdot(s, r))



Vector product of r and s vectors:
 73900
Vector product of r and s matrix:
 7000
Vector product of r and s matrix with complex numbers:
 (7000-800j)
Vector product of r and s matrix with complex numbers:
 (7000+800j)


### **Inner Product (np.inner())**

In [ ]:
# Inner product of two vectors using np.inner()
import numpy as np
r = np.array([10, 60, 30])
s = np.array([50, 30, 10])
print("1-D array r:\n",r)
print("1-D array s:\n",s)
print("Inner product of 1-D arrays r and s :\n",np.inner(r, s))

# Inner product of two matrices using np.inner()
import numpy as np
r = np.array([[10, 20], [30, 40]])
s = np.array([[50, 60], [70, 80]])
print("\n2-D arrays r:\n",r)
print("2-D arrays s:\n",s)
print("Inner product of 2-D arrays r and s :\n",np.inner(r, s))


1-D array r:
 [10 60 30]
1-D array s:
 [50 30 10]
Inner product of 1-D arrays r and s :
 2600

2-D arrays r:
 [[10 20]
 [30 40]]
2-D arrays s:
 [[50 60]
 [70 80]]
Inner product of 2-D arrays r and s :
 [[1700 2300]
 [3900 5300]]


### **Outer Product (np.outer())**

In [ ]:
# np.outer() function
import numpy as np
r = np.array([10, 60]) # 1-D array with 2 elements
s = np.array([50, 30, 10]) # 1-D array with 3 elements
print("Array r:\n",r)
print("Array s:\n",s)
# outer product of r and s will give a 2-D array of shape (2, 3)
print("Outer product of 1-D arrays r and s :\n",np.outer(r, s))

Array r:
 [10 60]
Array s:
 [50 30 10]
Outer product of 1-D arrays r and s :
 [[ 500  300  100]
 [3000 1800  600]]


### **Cross product (np.cross())**

In [ ]:
# np.cross() function
import numpy as np
r = np.array([10, 60, 80])
s = np.array([10, 20, 30])
print("Array r:\n",r)
print("Array s:\n",s)
# cross product of r and s
print("Cross product of 1-D arrays r and s :\n",np.cross(r, s))

Array r:
 [10 60 80]
Array s:
 [10 20 30]
Cross product of 1-D arrays r and s :
 [ 200  500 -400]


### **Kronecker product (np.kron())**

In [ ]:
# kronecker product np.kron() function
import numpy as np
A = np.array([[1], [4]])
B = np.array([[5, 6], [7, 8]])
print("Array A:\n",A)
print("Array B:\n",B)
print("Kronecker product of A and B:\n",np.kron(A, B))

Array A:
 [[1]
 [4]]
Array B:
 [[5 6]
 [7 8]]
Kronecker product of A and B:
 [[ 5  6]
 [ 7  8]
 [20 24]
 [28 32]]


### **Tensor dot product (np.tensordot())**

In [ ]:
#np.tensordot() function
import numpy as np
# Define tensors A and B
A = np.array([[[10, 20], [30, 40]], [[50, 60], [10, 80]]])
B = np.array([[[90, 80], [50, 60]], [[60, 40], [30, 20]]])

# Compute tensor dot product specifying the axes
# Summing over the last axis of A and the second-to-last axis of B
result = np.tensordot(A, B, axes=[2, 1])

print("Tensor A:\n", A)
print("Tensor B:\n", B)
print("Tensor dot product of A and B over specified axes:\n", result)


Tensor A:
 [[[10 20]
  [30 40]]

 [[50 60]
  [10 80]]]
Tensor B:
 [[[90 80]
  [50 60]]

 [[60 40]
  [30 20]]]
Tensor dot product of A and B over specified axes:
 [[[[1900 2000]
   [1200  800]]

  [[4700 4800]
   [3000 2000]]]


 [[[7500 7600]
   [4800 3200]]

  [[4900 5600]
   [3000 2000]]]]


### **Einstein Summation (np.einsum())**

In [ ]:
import numpy as np
# Example 1: Summing all elements in an array 'a'
a = np.array([10, 20, 30])
sum_a = np.einsum('i->', a)

# Example 2: Dot product of two vectors 'a' and 'b'
b = np.array([40, 50, 60])
dot_product = np.einsum('i,i->', a, b)

# Example 3: Element-wise multiplication of 'a' and 'b'
elementwise_mul = np.einsum('i,i->i', a, b)

# Example 4: Matrix multiplication of 'c' and 'd'
c = np.array([[10, 20], [30, 40]])
d = np.array([[50, 60], [70, 80]])
matrix_mul = np.einsum('ij,jk->ik', c, d)

# Example 5: Transposing matrix 'c'
transpose_c = np.einsum('ij->ji', c)

# Example 6: Trace of matrix 'c' (sum of diagonal elements)
trace_c = np.einsum('ii->', c)

# Example 7: Batch matrix multiplication

e = np.array([[[10, 20], [30, 40]], [[50, 60], [70, 80]]])
f = np.array([[[90, 80], [70, 60]], [[50, 40], [30, 20]]])
batch_matrix_mul = np.einsum('bij,bjk->bik', e, f)

# Printing results

print("Sum of 'a'", sum_a)
print("Dot product of 'a' and 'b'", dot_product)
print("Element-wise multiplication of 'a' and 'b'", elementwise_mul)
print("Matrix multiplication of 'c' and 'd'", matrix_mul)
print("Transpose of 'c'", transpose_c)
print("Trace of 'c'", trace_c)
print("Batch matrix multiplication of 'e' and 'f'", batch_matrix_mul )


Sum of 'a' 60
Dot product of 'a' and 'b' 3200
Element-wise multiplication of 'a' and 'b' [ 400 1000 1800]
Matrix multiplication of 'c' and 'd' [[1900 2200]
 [4300 5000]]
Transpose of 'c' [[10 30]
 [20 40]]
Trace of 'c' 50
Batch matrix multiplication of 'e' and 'f' [[[2300 2000]
  [5500 4800]]

 [[4300 3200]
  [5900 4400]]]


### **Efficient matrix chain multiplication (np.linalg.multi_dot())**

In [ ]:
#np.linal.multi_dot()
import numpy as np

# Define the matrices
A = np.random.rand(3, 5)
B = np.random.rand(5, 3)
C = np.random.rand(3, 10)

print("Matrix A:{} and shape is :{}\n".format(A, A.shape))
print("Matrix B:{} and shape is :{}\n".format(B, B.shape))
print("Matrix C:{} and shape is :{}\n".format(C, C.shape))

# Perform the multiplication
result = np.linalg.multi_dot([A, B, C])

print("dot product of A, B, C:{} and shape is :{}".format(result, result.shape))

Matrix A:[[0.88770358 0.95519742 0.75304508 0.58514805 0.7360644 ]
 [0.74045427 0.57779809 0.40859838 0.49359663 0.36335209]
 [0.3647216  0.19411415 0.98001893 0.62358153 0.58619818]] and shape is :(3, 5)

Matrix B:[[0.49375723 0.62359307 0.20390042]
 [0.7148769  0.24458808 0.14720917]
 [0.65689843 0.73678857 0.98623032]
 [0.3771475  0.97068498 0.60239296]
 [0.87396308 0.26851114 0.07730983]] and shape is :(5, 3)

Matrix C:[[0.1045326  0.00142511 0.24930762 0.38162991 0.24636146 0.51369375
  0.08161895 0.10876439 0.66698868 0.18031128]
 [0.35144485 0.48510638 0.95383444 0.0430357  0.50174132 0.38462256
  0.20661465 0.9678998  0.81429804 0.0198486 ]
 [0.0342677  0.94122024 0.07646266 0.51959198 0.43618527 0.67914725
  0.51125174 0.82639583 0.43698247 0.58741783]] and shape is :(3, 10)

dot product of A, B, C:[[1.05044976 2.41304051 2.74128331 1.80279163 2.31123433 3.08537101
  1.39129953 3.5275742  4.01425135 1.35464246]
 [0.71557806 1.62830721 1.8728092  1.15666655 1.54570823 2.0211738

### **np.linalg.matrix_power()**

In [ ]:
# np.linalg.matrix_power()
import numpy as np
# Define the matrix
A = np.array([[1, 2], [3, 4]])
# Compute the matrix power
result = np.linalg.matrix_power(A, 3)

print("Matrix A:\n", A)
print("Matrix power of A to the 3:\n", result)

Matrix A:
 [[1 2]
 [3 4]]
Matrix power of A to the 3:
 [[ 37  54]
 [ 81 118]]


## **Matrix Eigenvalues & Eigenvectors**

In [ ]:
# np.linalg.eig()
import numpy as np

A = np.array([[0, 20],
              [12, 50]])

print('Matrix A:\n', A)

eig_value,eig_vector=np.linalg.eig(a)
print('E-value of matrix A:\n', eig_value)
print('E-vector of matrix A:\n', eig_vector)

Matrix A:
 [[ 0 20]
 [12 50]]
E-value of matrix A:
 [-4.41088234 54.41088234]
E-vector of matrix A:
 [[-0.97653284 -0.34500485]
 [ 0.21536857 -0.9386009 ]]


## **Decompositions**

### **QR decomposition**

In [ ]:
# QR decomposition
import numpy as np

# define the matrix
A = np.array([[1, 2], [3, 4], [5, 6]])
print("Matrix A:\n", A)

Q, R = np.linalg.qr(A)

print("Orthogonal matrix Q:\n", Q)
print("Upper triangular matrix R:\n", R)


Matrix A:
 [[1 2]
 [3 4]
 [5 6]]
Orthogonal matrix Q:
 [[-0.16903085  0.89708523]
 [-0.50709255  0.27602622]
 [-0.84515425 -0.34503278]]
Upper triangular matrix R:
 [[-5.91607978 -7.43735744]
 [ 0.          0.82807867]]


### **Cholesky Decomposition**

In [ ]:
# Cholesky Decomposition np.linalg.cholesky(A)
import numpy as np
A = np.array([[10,-20j],[20j,50]])
print("Matrix A:\n", A)

L = np.linalg.cholesky(A)
print("Lower triangular matrix L:\n", L)


# verify that L * L.H = A
A= np.dot(L, L.T.conj())
print("Matrix A:\n", A)

Matrix A:
 [[10. +0.j -0.-20.j]
 [ 0.+20.j 50. +0.j]]
Lower triangular matrix L:
 [[3.16227766+0.j         0.        +0.j        ]
 [0.        +6.32455532j 3.16227766+0.j        ]]
Matrix A:
 [[10. +0.j  0.-20.j]
 [ 0.+20.j 50. +0.j]]


### **Singular Value Decomposition (np.linalg.svd())**

In [ ]:
#SVD
import numpy as np
# Define a matrix
A = np.array([[10, 20], [30, 40], [50, 60]])
print("Matrix A:\n", A)

# Compute the SVD
U, Sigma, VH = np.linalg.svd(A)
print("U :\n", U)
print("Sigma:\n", Sigma)
print("VH:\n", VH)

# Reconstruct the orginal matrix
Sigma_digmat = np.zeros((A.shape[0],A.shape[1]))
np.fill_diagonal(Sigma_digmat, Sigma)
A_recon  = np.dot(U,np.dot(Sigma_digmat,VH))
print("Reconstructed matrix:\n", A_recon)

Matrix A:
 [[10 20]
 [30 40]
 [50 60]]
U :
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Sigma:
 [95.25518092  5.14300581]
VH:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
Reconstructed matrix:
 [[10. 20.]
 [30. 40.]
 [50. 60.]]


## **Solving Linear systems using NumPy**

### **np.linalg.solve()**

In [ ]:
# np.linalg.solve()
#10x + 20y = 50
#30x + 40y = 60
import numpy as np

A = np.array([[10, 20], [30, 40]])
b = np.array([50, 60])

x = np.linalg.solve(A, b)

print("Matrix A:\n", A)
print("Vector b:\n", b)
print("Solution of the linear system:\n", x)


Matrix A:
 [[10 20]
 [30 40]]
Vector b:
 [50 60]
Solution of the linear system:
 [-4.   4.5]


### **np.linalg.lstsq()**

In [ ]:
import numpy as np

# np.linalg.lstsq()

# Defining a non-square matrix A (overdetermined system)
A = np.array([[10, 20], [30, 40], [70, 80]])
# Defining vector b
b = np.array([50, 60, 90])

# Using np.linalg.lstsq() to find the least squares solution
x, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)

print("Matrix A:\n", A)
print("Vector b:\n", b)
print("Solution of the linear system:\n", x)
print("Residuals:\n", residuals)
print("Rank of the matrix:\n", rank)
print("Singular values:\n", s)


Matrix A:
 [[10 20]
 [30 40]
 [70 80]]
Vector b:
 [50 60 90]
Solution of the linear system:
 [-3.5         4.17857143]
Residuals:
 [7.14285714]
Rank of the matrix:
 2
Singular values:
 [119.41830399   6.26647216]
