### **Copies and Views**

In [ ]:
#Copying an array
original_array = [10, 20, 30, 40, 50]
print("Original Array:", original_array)

# Creating a copy of the original array
array_copy = original_array.copy()
print("Array Copy:", array_copy)

# Modifying the copy
array_copy[0] = 11
print("Modified Array Copy:", array_copy)

# Original array remains unchanged
print("Original Array After Modifying Copy:", original_array)


Original Array: [10, 20, 30, 40, 50]
Array Copy: [10, 20, 30, 40, 50]
Modified Array Copy: [11, 20, 30, 40, 50]
Original Array After Modifying Copy: [10, 20, 30, 40, 50]


In [ ]:
import numpy as np

# Original array
original_array = np.array([10, 20, 30, 40, 50])
print("Original Array:", original_array)

# Creating a view of the original array
array_view = original_array.view()
print("Array View:", array_view)

# Modifying the view
array_view[0] = 99
print("Modified Array View:", array_view)

# Original array is also modified
print("Original Array After Modification:", original_array)


Original Array: [10 20 30 40 50]
Array View: [10 20 30 40 50]
Modified Array View: [99 20 30 40 50]
Original Array After Modification: [99 20 30 40 50]


### **Reshaping and Resizing the NumPy Arrays**

In [ ]:
#Reshaping 1D arry to 2D array
import numpy as np
input_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
reshaped_array = input_array.reshape(3,3)

print("Original Array:\n",input_array)
print("Reshaped Array:\n",reshaped_array)




Original Array:
 [1 2 3 4 5 6 7 8 9]
Reshaped Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
reshaped_array = input_array.reshape(3,2)

ValueError: ignored

In [ ]:
import numpy as np

# Original array with 12 elements
original_array = np.arange(9)
print("Original Array:\n", original_array)

# Resizing the array to have 16 elements - increases size, repeats elements
resized_larger = np.resize(original_array, (4,4))
print("Resized Array (larger):\n", resized_larger)

# Resizing the array to have 6 elements - decreases size, truncates elements
resized_smaller = np.resize(original_array, (2,2))
print("Resized Array (smaller):\n", resized_smaller)


Original Array:
 [0 1 2 3 4 5 6 7 8]
Resized Array (larger):
 [[0 1 2 3]
 [4 5 6 7]
 [8 0 1 2]
 [3 4 5 6]]
Resized Array (smaller):
 [[0 1]
 [2 3]]


## **Inserting, appending, and deleting the element(s) from the array.**

In [ ]:
#insert(), append(), delete()
import numpy as np

# Original array
original_array = np.array([10, 20, 40, 50])
print("Original Array:", original_array)

# Inserting a value 12 at index 2
new_array = np.insert(original_array, 2, 12)
print("After Insertion:", new_array)


Original Array: [10 20 40 50]
After Insertion: [10 20 12 40 50]


In [ ]:
import numpy as np

# Original array
original_array = np.array([10, 20, 40, 50])
print("Original Array:", original_array)

# Appending a value 6 to the original array
appended_array = np.append(original_array, 11)
print("After Appending:", appended_array)


Original Array: [10 20 40 50]
After Appending: [10 20 40 50 11]


In [ ]:
import numpy as np

# Original array
original_array = np.array([10, 20, 40, 50])
print("Original Array:", original_array)

# Appending a value 6 to the original array
appended_array = np.append(original_array, 11)
print("After Appending:", appended_array)


Original Array: [10 20 40 50]
After Appending: [10 20 40 50 11]


In [ ]:
# append at axis=1
import numpy as np

# Creating a 2D array
original_array = np.array([[10, 20], [30, 40]])
print("Original Array:\n", original_array)

# Creating a new column to append
new_column = np.array([[50], [60]])
print("New Column:\n", new_column)

# Appending the new column
appended_array = np.append(original_array, new_column, axis=1)
print("After Appending:\n", appended_array)

Original Array:
 [[10 20]
 [30 40]]
New Column:
 [[50]
 [60]]
After Appending:
 [[10 20 50]
 [30 40 60]]


In [ ]:
import numpy as np

# Original array
original_array = np.array([10, 20, 40, 50])
print("Original Array:", original_array)

# Deleting a element at index 2
deleted_array = np.delete(original_array, 2)
print("After Deletion:", deleted_array)


Original Array: [10 20 40 50]
After Deletion: [10 20 50]


### **Flattening the Arrays**

In [ ]:
import numpy as np

# Creating a 2D array
array_2d = np.array([[10, 20, 30], [40, 50, 60]])
print("Original array:\n", array_2d)

# Flattening the array
flattened_array = array_2d.flatten()
print("Flattened Array:", flattened_array)


Original array:
 [[10 20 30]
 [40 50 60]]
Flattened Array: [10 20 30 40 50 60]


In [ ]:
import numpy as np

# Creating a 2D array
array_2d = np.array([[10, 20, 30], [40, 50, 60]])
print("Original array:\n", array_2d)

raveled_array = array_2d.ravel()
print("Raveled Array:", raveled_array)


Original array:
 [[10 20 30]
 [40 50 60]]
Raveled Array: [10 20 30 40 50 60]


## **Concatenating and Splitting Arrays**

### **Concatenating**

In [ ]:
import numpy as np

# Creating two 2D arrays
arr_1 = np.array([[10, 20], [30, 40]])
arr_2 = np.array([[50, 60], [70, 80]])

print("Array 1:\n", arr_1)
print("Array 2:\n", arr_2)

# Concatenating along the first axis (axis=0, row-wise)
concatenated_array_axis_0 = np.concatenate((arr_1, arr_2), axis=0)
print("Concatenated along axis 0:\n", concatenated_array_axis_0)

# Concatenating along the second axis (axis=1, column-wise)
concatenated_array_axis_1 = np.concatenate((arr_1, arr_2), axis=1)
print("Concatenated along axis 1:\n", concatenated_array_axis_1)

Array 1:
 [[10 20]
 [30 40]]
Array 2:
 [[50 60]
 [70 80]]
Concatenated along axis 0:
 [[10 20]
 [30 40]
 [50 60]
 [70 80]]
Concatenated along axis 1:
 [[10 20 50 60]
 [30 40 70 80]]


In [ ]:
import numpy as np

# Creating two 2D arrays
arr_1 = np.array([[10, 20], [30, 40]])
arr_2 = np.array([[50, 60], [70, 80]])

print("Array 1:\n", arr_1)
print("Array 2:\n", arr_2)

# Horizontal stacking
hstacked_array = np.hstack((arr_1, arr_2))
print("Horizontal Stacked Array:\n", hstacked_array)

# Vertical stacking
vstacked_array = np.vstack((arr_1, arr_2))
print("Vertical Stacked Array:\n", vstacked_array)

Array 1:
 [[10 20]
 [30 40]]
Array 2:
 [[50 60]
 [70 80]]
Horizontal Stacked Array:
 [[10 20 50 60]
 [30 40 70 80]]
Vertical Stacked Array:
 [[10 20]
 [30 40]
 [50 60]
 [70 80]]


#### **Spliting Arrays**

In [ ]:
# spliting an array
import numpy as np
arr_1 = np.array([[10, 20], [30, 40], [50, 60], [70, 80]])
print("Original Array:\n", arr_1)

# Splitting the array using np.split()
split_array = np.split(arr_1, 4,axis=0)
print("Splited Array:\n", split_array)

Original Array:
 [[10 20]
 [30 40]
 [50 60]
 [70 80]]
Splited Array:
 [array([[10, 20]]), array([[30, 40]]), array([[50, 60]]), array([[70, 80]])]


In [ ]:
# spliting an array
import numpy as np
arr_1 = np.array([[10, 20,10], [30, 40,23], [50, 60,56], [70, 80,66]])
print("Original Array:\n", arr_1)

# Splitting the array using np.split()
split_array = np.split(arr_1, 3,axis=1)
print("Splited Array:\n", split_array)

Original Array:
 [[10 20 10]
 [30 40 23]
 [50 60 56]
 [70 80 66]]
Splited Array:
 [array([[10],
       [30],
       [50],
       [70]]), array([[20],
       [40],
       [60],
       [80]]), array([[10],
       [23],
       [56],
       [66]])]


In [ ]:
import numpy as np
arr_1 = np.array([[10, 20,10], [30, 40,23], [50, 60,56], [70, 80,66]])
print("Original Array:\n", arr_1)

# Splitting into 3 parts (unequal division)
unequal_split_arrays = np.array_split(arr_1, 3)
print("Unequal Split Arrays:", unequal_split_arrays)


Original Array:
 [[10 20]
 [30 40]
 [50 60]
 [70 80]]
Unequal Split Arrays: [array([[10, 20],
       [30, 40]]), array([[50, 60]]), array([[70, 80]])]


In [ ]:
# spliting an array
import numpy as np
arr_1 = np.array([[10, 20, 78], [30, 40, 89], [50, 60, 67], [70, 80, 90]])
print("Original Array:\n", arr_1)

# Splitting the array using np.hsplit()
h_split_arrays = np.hsplit(arr_1, 3)
print("Horizontally Split Arrays:", h_split_arrays)


Original Array:
 [[10 20 78]
 [30 40 89]
 [50 60 67]
 [70 80 90]]
Horizontally Split Arrays: [array([[10],
       [30],
       [50],
       [70]]), array([[20],
       [40],
       [60],
       [80]]), array([[78],
       [89],
       [67],
       [90]])]


In [ ]:
# spliting an array
import numpy as np
arr_1 = np.array([[10, 20], [30, 40], [50, 60], [70, 80]])
print("Original Array:\n", arr_1)

# Splitting the array using np.hsplit()
v_split_arrays = np.vsplit(arr_1, 4)
print("Horizontally Split Arrays:", v_split_arrays)


Original Array:
 [[10 20]
 [30 40]
 [50 60]
 [70 80]]
Horizontally Split Arrays: [array([[10, 20]]), array([[30, 40]]), array([[50, 60]]), array([[70, 80]])]


### **Transpose the array in Numpy**

In [ ]:
import numpy as np
# creating 2d array
arr_2d = np.array([[10, 20, 30], [40, 50, 60]])
print("Original array:\n", arr_2d)

# Transposing the array
transposed_array = np.transpose(arr_2d)
print("Transposed array:\n", transposed_array)


Original array:
 [[10 20 30]
 [40 50 60]]
Transposed array:
 [[10 40]
 [20 50]
 [30 60]]


In [ ]:
# tranposing 3d array
import numpy as np
arr_3d = np.array([[[10, 20], [30, 40]], [[50, 60], [70, 80]]])
print("Original array:\n", arr_3d)

# Transposing along the first and second axes means it will transpose the first two axes
transposed_array = np.transpose(arr_3d, (1, 0, 2))
print("Transposed array:\n", transposed_array)


Original array:
 [[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
Transposed array:
 [[[10 20]
  [50 60]]

 [[30 40]
  [70 80]]]


In [ ]:
arr_3d.shape

(2, 2, 2)

In [ ]:
import numpy as np

# Creating a 2D array
arr_2d = np.array([[10, 20], [30, 40]])
print("Original array:\n", arr_2d)

# Using array.T
transposed_2d = arr_2d.T
print("Transposed array:\n", transposed_2d)


Original array:
 [[10 20]
 [30 40]]
Transposed array:
 [[10 30]
 [20 40]]


### **Arithmetic Operators and functions in NumPy**

In [ ]:
import numpy as np
arr1 = np.array([[10, 20], [30, 40]])
arr2 = np.array([[50, 60], [70, 80]])
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)


#addition
result = arr1 + arr2
print("Addition with '+' operator:\n", result)
result = np.add(arr1, arr2)
print("Addition with add() function:\n", result)

#subtraction
result = arr1 - arr2
print("Subtraction with '-' operator:\n", result)
result = np.subtract(arr1, arr2)
print("Subtraction with subtract() function:\n", result)

#multiplication
result = arr1 * arr2
print("Multiplication with '*' operator:\n", result)
result = np.multiply(arr1, arr2)
print("Multiplication with multiply() function:\n", result)

#division
result = arr1 / arr2
print("Division with '/' operator:\n", result)
result = np.divide(arr1, arr2)
print("Division with divide() function:\n", result)

#floor division
result = arr1 // arr2
print("Floor Division with '//' operator:\n", result)
result = np.floor_divide(arr1, arr2)
print("Floor Division with floor_divide() function:\n", result)

#mod
result = arr1 % arr2
print("Mod with '%' operator:\n", result)
result = np.mod(arr1, arr2)
print("Mod with mod() function:\n", result)

#power
result = arr1 ** arr2
print("Power with '**' operator:\n", result)
result = np.power(arr1, arr2)
print("Power with power() function:\n", result)

Array 1:
 [[10 20]
 [30 40]]
Array 2:
 [[50 60]
 [70 80]]
Addition with '+' operator:
 [[ 60  80]
 [100 120]]
Addition with add() function:
 [[ 60  80]
 [100 120]]
Subtraction with '-' operator:
 [[-40 -40]
 [-40 -40]]
Subtraction with subtract() function:
 [[-40 -40]
 [-40 -40]]
Multiplication with '*' operator:
 [[ 500 1200]
 [2100 3200]]
Multiplication with multiply() function:
 [[ 500 1200]
 [2100 3200]]
Division with '/' operator:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Division with divide() function:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Floor Division with '//' operator:
 [[0 0]
 [0 0]]
Floor Division with floor_divide() function:
 [[0 0]
 [0 0]]
Mod with '%' operator:
 [[10 20]
 [30 40]]
Mod with mod() function:
 [[10 20]
 [30 40]]
Power with '**' operator:
 [[-5376172055173529600                    0]
 [                   0                    0]]
Power with power() function:
 [[-5376172055173529600                    0]
 [                   0        

In [ ]:
import numpy as np

# Creating two arrays for demonstration
arr1 = np.array([10, 20, 30])
arr2 = np.array([40, 50, 60])
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

# Creating an empty array to hold the result
result = np.empty_like(arr1)


# Performing an arithmetic operation using the out parameter
np.add(arr1, arr2, out=result)
print("Result array:\n", result)


Array 1:
 [10 20 30]
Array 2:
 [40 50 60]
Result array:
 [50 70 90]


### **Broadcasting Rules in NumPy**

In [ ]:
#Rule#1: Compare Dimensions
import numpy as np
arr1 = np.array([[10, 20, 30],[40, 50, 60]])
arr2 = np.array([70, 80, 90])

print("arr1:\n", arr1)
print("shape of arr1 is", arr1.shape)

print("\narr2:\n", arr2)
print("shape of arr2 is:", arr2.shape)


result = arr1 + arr2
print("\nResult:\n", result)

arr1:
 [[10 20 30]
 [40 50 60]]
shape of arr1 is (2, 3)

arr2:
 [70 80 90]
shape of arr2 is: (3,)

Result:
 [[ 80 100 120]
 [110 130 150]]


### **Aggregation & Statistical Functions In NumPy**

In [ ]:
#Aggregation  and Statistical Functions in Numpy
import numpy as np
array_2d = np.array([[10, 20, 30], [40, 50, 60]])
print("Original array:\n", array_2d)

# Sum of elements






Original array:
 [[10 20 30]
 [40 50 60]]


In [ ]:


#



Original array:
 [[10 20 30]
 [40 50 60]]


In [ ]:
#Aggregation  and Statistical Functions in Numpy

import numpy as np
array_2d = np.array([[10, 20, 30], [40, 50, 60]])
print("Original array:\n", array_2d)

# sum()
result = np.sum(array_2d)
print("Sum of elements:\n", result)

# prod()
result = np.prod(array_2d)
print("Product of elements:\n", result)

# cumsum()
result = np.cumsum(array_2d)
print("Cumulative sum:\n", result)

# cumprod()
result = np.cumprod(array_2d)
print("Cumulative product:\n", result)

# min()
result = np.min(array_2d)
print("Minimum element:\n", result)

# max()
result = np.max(array_2d)
print("Maximum element:\n", result)

# argmin()
result = np.argmin(array_2d)
print("Index of minimum element:\n", result)

# argmax()
result = np.argmax(array_2d)
print("Index of maximum element:\n", result)

# mean()
result = np.mean(array_2d)
print("Mean of elements:\n", result)

# median()
result = np.median(array_2d)
print("Median of elements:\n", result)

# percentile()
result = np.percentile(array_2d, 50)
print("50th percentile:\n", result)

# quantile()
result = np.quantile(array_2d, 0.5)
print("0.5th quantile:\n", result)

# all()
result = np.all(array_2d > 0)
print("Are all elements greater than 0:\n", result)

# any()
result = np.any(array_2d > 0)
print("Are any elements greater than 0:\n", result)

# std()
result = np.std(array_2d)
print("Standard deviation:\n", result)

# var()
result = np.var(array_2d)
print("Variance:\n", result)

# average()
result = np.average(array_2d)
print("Average:\n", result)

# ptp()
result = np.ptp(array_2d)
print("Peak-to-peak value:\n", result)

# corrcoef()
result = np.corrcoef(array_2d)
print("Correlation coefficient:\n", result)


Sum of elements:
 210
Product of elements:
 720000000
Cumulative sum:
 [ 10  30  60 100 150 210]
Cumulative product:
 [       10       200      6000    240000  12000000 720000000]
Minimum element:
 10
Maximum element:
 60
Index of minimum element:
 0
Index of maximum element:
 5
Mean of elements:
 35.0
Median of elements:
 35.0
50th percentile:
 35.0
0.5th quantile:
 35.0
Are all elements greater than 0:
 True
Are any elements greater than 0:
 True
Standard deviation:
 17.07825127659933
Variance:
 291.6666666666667
Average:
 35.0
Peak-to-peak value:
 50
Correlation coefficient:
 [[1. 1.]
 [1. 1.]]


In [ ]:
#Aggregation Functions in NumPy

import numpy as np
array_2d = np.array([[10, 20, 30], [40, 50, 60]])
print("Original array:\n", array_2d)
# sum()
result = np.sum(array_2d)
print("Sum of elements:\n", result)
# prod()
result = np.prod(array_2d)
print("Product of elements:\n", result)
# cumsum()
result = np.cumsum(array_2d)
print("Cumulative sum:\n", result)
# cumprod()
result = np.cumprod(array_2d)
print("Cumulative product:\n", result)
# min()
result = np.min(array_2d)
print("Minimum element:\n", result)
# max()
result = np.max(array_2d)
print("Maximum element:\n", result)
# argmin()
result = np.argmin(array_2d)
print("Index of minimum element:\n", result)
# argmax()
result = np.argmax(array_2d)
print("Index of maximum element:\n", result)
# all()
result = np.all(array_2d > 0)
print("Are all elements greater than 0:\n", result)
# any()
result = np.any(array_2d > 0)
print("Are any elements greater than 0:\n", result)


Original array:
 [[10 20 30]
 [40 50 60]]
Sum of elements:
 210
Product of elements:
 720000000
Cumulative sum:
 [ 10  30  60 100 150 210]
Cumulative product:
 [       10       200      6000    240000  12000000 720000000]
Minimum element:
 10
Maximum element:
 60
Index of minimum element:
 0
Index of maximum element:
 5
Are all elements greater than 0:
 True
Are any elements greater than 0:
 True


In [ ]:
#Statistical Functions in Numpy
import numpy as np
array_2d = np.array([[10, 20, 30], [40, 50, 60]])
print("Original array:\n", array_2d)
# mean()
result = np.mean(array_2d)
print("Mean of elements:\n", result)
# median()
result = np.median(array_2d)
print("Median of elements:\n", result)
# percentile()
result = np.percentile(array_2d, 50)
print("50th percentile:\n", result)
# quantile()
result = np.quantile(array_2d, 0.5)
print("0.5th quantile:\n", result)
# std()
result = np.std(array_2d)
print("Standard deviation:\n", result)
# var()
result = np.var(array_2d)
print("Variance:\n", result)
# average()
result = np.average(array_2d)
print("Average:\n", result)
# ptp()
result = np.ptp(array_2d)
print("Peak-to-peak value:\n", result)
# corrcoef()
result = np.corrcoef(array_2d)
print("Correlation coefficient:\n", result)

Original array:
 [[10 20 30]
 [40 50 60]]
Mean of elements:
 35.0
Median of elements:
 35.0
50th percentile:
 35.0
0.5th quantile:
 35.0
Standard deviation:
 17.07825127659933
Variance:
 291.6666666666667
Average:
 35.0
Peak-to-peak value:
 50
Correlation coefficient:
 [[1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np
array_2d = np.array([[10, 20, 30], [40, 50, 60]])
print("Original array:\n", array_2d)

sum_along_axis_0 = np.sum(array_2d, axis=0)
print('sum_along_axis_0 :',sum_along_axis_0)

sum_along_axis_1 = np.sum(array_2d, axis=1)
print("sum_along_axis_1:",sum_along_axis_1)


Original array:
 [[10 20 30]
 [40 50 60]]
sum_along_axis_0 : [50 70 90]
sum_along_axis_1: [ 60 150]


In [ ]:
# Set operations in numpy
import numpy as np
array_1d = np.array([10, 20, 30, 40, 50, 60, 70, 50,10,20,80, 90])
print("Original array:\n", array_1d)

# unique()
result = np.unique(array_1d)
print("Unique elements:\n", result)

Original array:
 [10 20 30 40 50 60 70 50 10 20 80 90]
Unique elements:
 [10 20 30 40 50 60 70 80 90]


### **Intersection, Union, and Differences**

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([30, 40, 50, 60])
print("Array 1:", arr1)
print("Array 2:", arr2)

# setdiff1d()
intersection = np.intersect1d(arr1, arr2)
print("Intersection:", intersection)


Array 1: [10 20 30 40]
Array 2: [30 40 50 60]
Intersection: [30 40]


In [ ]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([30, 40, 50, 60])
print("Array 1:", arr1)
print("Array 2:", arr2)

# union1d()
union = np.union1d(arr1, arr2)
print("Union:", union)


Array 1: [10 20 30 40]
Array 2: [30 40 50 60]
Union: [10 20 30 40 50 60]


In [ ]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([30, 40, 50, 60])
print("Array 1:", arr1)
print("Array 2:", arr2)

# setdiff1d()
set_difference = np.setdiff1d(arr1, arr2)
print("Set Difference (arr1-arr2):", set_difference)

Array 1: [10 20 30 40]
Array 2: [30 40 50 60]
Set Difference (arr1-arr2): [10 20]


In [ ]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([30, 40, 50, 60])
print("Array 1:", arr1)
print("Array 2:", arr2)

sym_diff = np.setxor1d(arr1, arr2)
print("Symmetric Difference:", sym_diff)


Array 1: [10 20 30 40]
Array 2: [30 40 50 60]
Symmetric Difference: [10 20 50 60]


### **Membership Tests**

In [ ]:
import numpy as np

arr = np.array([10, 20, 30,  40, 50])
print("Original array:", arr)

element = 30
is_member = np.isin(element, arr)
print(f"Is {element} in the array? {is_member}")

elements = [20, 40, 60]
are_members = np.isin(elements, arr)
print(f"Are {elements} in the array? {are_members}")


Original array: [10 20 30 40 50]
Is 30 in the array? True
Are [20, 40, 60] in the array? [ True  True False]


In [ ]:
import numpy as np

# Define two arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([30, 40, 60, 70])

# Use np.in1d to check if elements of arr1 are in arr2
result = np.in1d(arr1, arr2)

print("arr1:", arr1)
print("arr2:", arr2)
print("Is each element of arr1 in arr2?", result)


arr1: [10 20 30 40 50]
arr2: [30 40 60 70]
Is each element of arr1 in arr2? [False False  True  True False]


###	**Finiteness and Special Values:**

In [ ]:
import numpy as np

arr = np.array([11, np.nan, np.inf, -np.inf, 12])
print("Original array:", arr)
finite_elements = np.isfinite(arr)
print("Finite Elements:", finite_elements)


Original array: [ 11.  nan  inf -inf  12.]
Finite Elements: [ True False False False  True]


In [ ]:
import numpy as np

arr = np.array([11, np.nan, np.inf, -np.inf, 12])
print("Original array:", arr)
infinite_elements = np.isinf(arr)
print("Infinite Elements:", infinite_elements)


Original array: [ 11.  nan  inf -inf  12.]
Infinite Elements: [False False  True  True False]


In [ ]:
import numpy as np

arr = np.array([11, np.nan, np.inf, -np.inf, 12])
print("Original array:", arr)
nan_elements = np.isnan(arr)
print("NaN Elements:", nan_elements)


Original array: [ 11.  nan  inf -inf  12.]
NaN Elements: [False  True False False False]


### **Logical functions in NumPy:**

In [ ]:
import numpy as np
array_1d = np.array([10, 20, 30, 40, 50])
print("Original array:\n", array_1d)

# logical_and()
result = np.logical_and(array_1d > 20, array_1d < 50)
print("Logical and:\n", result)

Original array:
 [10 20 30 40 50]
Logical and:
 [False False  True  True False]


In [ ]:
import numpy as np
array_1d = np.array([10, 20, 30, 40, 50])
print("Original array:\n", array_1d)

# logical_or()
result = np.logical_or(array_1d > 20, array_1d < 50)
print("Logical or:\n", result)

Original array:
 [10 20 30 40 50]
Logical or:
 [ True  True  True  True  True]


In [ ]:
import numpy as np
array_1d = np.array([10, 20, 30, 40, 50])
print("Original array:\n", array_1d)

# logical_not()
result = np.logical_not(array_1d > 20)
print("Logical not:\n", result)

Original array:
 [10 20 30 40 50]
Logical not:
 [ True  True False False False]


In [ ]:
import numpy as np
array_1d = np.array([10, 20, 30, 40, 50])
print("Original array:\n", array_1d)

# logical_xor()
result = np.logical_xor(array_1d > 20, array_1d < 50)
print("Logical xor:\n", result)

Original array:
 [10 20 30 40 50]
Logical xor:
 [ True  True False False  True]


### **Sorting in NumPy:**

In [ ]:
# sorting an array in ascending order
import numpy as np
unsorted_array = np.array([10, 50, 20, 40, 30])
print("Original array:\n", array_1d)

# sort()
sorted_array = np.sort(unsorted_array)
print("Sorted array:\n", sorted_array)

Original array:
 [10 50 20 40 30]
Sorted array:
 [10 20 30 40 50]


In [ ]:
# inplace sorting an array in ascending order
import numpy as np
arr = np.array([10, 50, 20, 40, 30])
print("Original array:\n", array_1d)

# using sort() to sort an array inplace
arr.sort()
print("Sorted array:\n", arr)


Original array:
 [10 50 20 40 30]
Sorted array:
 [10 20 30 40 50]


In [ ]:
import numpy as np
arr = np.array([10, 50, 20, 40, 30])
print("Original array:\n", array_1d)

# using argsort()
result = np.argsort(arr)
print("Sorted array indices:\n", result)


Original array:
 [10 50 20 40 30]
Sorted array indices:
 [0 2 4 3 1]


In [ ]:
import numpy as np
array_2d = np.array([[30, 80, 10], [60, 50, 40]])
print("Original array:\n", array_2d)

# using sort() with axis=0
sorted_array = np.sort(array_2d, axis=0)
print("Sorted array along the axis=0:\n", sorted_array)

# using sort() with axis=1
sorted_array = np.sort(array_2d, axis=1)
print("Sorted array along the axis=1:\n", sorted_array)

Original array:
 [[30 80 10]
 [60 50 40]]
Sorted array along the axis=0:
 [[30 50 10]
 [60 80 40]]
Sorted array along the axis=1:
 [[10 30 80]
 [40 50 60]]


### **Searching in NumPy**

In [ ]:
import numpy as np
arr = np.array([0,11, 8, 12, 2, 29, 1, 16, 0])
print("Original array:\n", arr)
nonzero_elements = np.nonzero(arr)
print("Indices of nonzero elements:\n", nonzero_elements)

Original array:
 [ 0 11  8 12  2 29  1 16  0]
Indices of nonzero elements:
 (array([1, 2, 3, 4, 5, 6, 7]),)


In [ ]:
# np.where() function and its various use cases
import numpy as np

# Creating a sample array
arr = np.array([11, 8, 12, 2, 29, 1, 16])
print("Original array:\n", arr)

# Variation 1: Finding indices where elements are greater than 5
indices = np.where(arr > 5)
print("\nIndices where elements are greater than 5:", indices)

# Variation 2: Creating a new array with conditional replacement
# 1 if arr > 5, -1 otherwise
arr_filtered = np.where(arr > 5, 1, -1)
print("\nNew array with conditional replacement:", arr_filtered)

# Variation 3: Creating a new array with multiple conditional replacements
# 1 if arr > 7, -1 if arr < 3, otherwise 0
nested_arr = np.where(arr > 7, 1, np.where(arr < 3, -1, 0))
print("\nArray with multiple conditional replacements:", nested_arr)


Original array:
 [11  8 12  2 29  1 16]

Indices where elements are greater than 5: (array([0, 1, 2, 4, 6]),)

New array with conditional replacement: [ 1  1  1 -1  1 -1  1]

Array with multiple conditional replacements: [ 1  1  1 -1  1 -1  1]


In [ ]:
#np.searchsorted() function\
import numpy as np

# Creating a sorted array
sorted_array = np.array([10, 30, 50, 70, 90])
print("Sorted array:\n", sorted_array)

# Values to be inserted
values_to_insert = [20, 60, 100]
print("Values to be inserted:\n", values_to_insert)

# Using np.searchsorted
insert_positions = np.searchsorted(sorted_array, values_to_insert)
print("Indices to insert values:", insert_positions)


Sorted array:
 [10 30 50 70 90]
Values to be inserted:
 [20, 60, 100]
Indices to insert values: [1 3 5]
