In [ ]:
import numpy as np

In [ ]:
import numpy as np

# Python List Indexing
list_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
# Accessing the third element in the second list
print("List Indexing: ", list_2d[1][2])

# NumPy Array Indexing
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Directly accessing the element in the second row, third column
print("NumPy Array Indexing: ", array_2d[1, 2])

List Indexing:  6
NumPy Array Indexing:  6


### **Negative Indexing**

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print("input original array:", arr)
# Accessing elements using negative indexing
last_element = arr[-1]  # Access the last element (50)
second_to_last = arr[-2]  # Access the second-to-last element (40)
third_to_last = arr[-3]  # Access the third-to-last element (30)

print("last element:", last_element)
print("second to last element:", second_to_last)
print("third to last element:", third_to_last)

input original array: [10 20 30 40 50]
last element: 50
second to last element: 40
third to last element: 30


In [ ]:
import numpy as np
arr = np.array([1, 6, 3, 4, 5])

print("input array:", arr)
print("elements where value is greater than 4:",arr[arr > 4])


input array: [1 6 3 4 5]
elements where value is greater than 4: [6 5]


In [ ]:
print ("input array:", arr)
index = np.array([True, False, True, False, True])
print("elements where index is True:", arr[index])


input array: [1 6 3 4 5]
elements where index is True: [1 3 5]


In [ ]:
print("input array:", arr)
print("even elements:",arr[arr % 2 == 0])


input array: [1 6 3 4 5]
even elements: [6 4]


### **Fancy Indexing with NumPy**

In [ ]:
import numpy as np

arr = np.array([100, 200, 300, 400, 500])
print("input original array:", arr)
indices = np.array([1, 3, 4])

selected_elements = arr[indices]
print("selected elements:",selected_elements)


input original array: [100 200 300 400 500]
selected elements: [200 400 500]


## **Slicing un NUmpY array**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
sliced_elements = arr[0:2]  # Start index is 0, stop index is 2 (exclusive)
print(sliced_elements)


[1 2]


In [ ]:
# select the 2nd element from last in array
import numpy as np
arr = np.array([1, 6, 3, 4, 5])
print("select the 2nd elemnt from last in array:", arr[-2])

## **Extracting the first 'n' elements from NumPy array**

In [ ]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Use slicing to get the first 4  elements
first_four_elements_1 = arr[:4]
first_four_elements_2 = arr[0:4]

print("first four element using slicing arr[:4]  ->", first_four_elements_1)
print("first four element using slicing arr[0:4] ->",first_four_elements_2)


first four element using slicing arr[:4]  -> [1 2 3 4]
first four element using slicing arr[0:4] -> [1 2 3 4]


### **Extracting the elements from index m to index n NumPy array**

In [ ]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Use slicing to get elements from index 2 to index 5 (inclusive)
extracted_elements = arr[2:6] #arr[m:n+1]

print(extracted_elements)


[3 4 5 6]


### **Extracting all elements from the NumPy array**

In [ ]:
import numpy as np

# Create a NumPy array
arr = np.array([10, 20, 30, 40, 50])
print(" Original array:", arr)

# Extract all elements using slicing notation [:]
all_elements_1 = arr[:]

# Extract all elements using slicing notation [::]
all_elements_2 = arr[::]


# Extract all elements using slicing notation [0:]
all_elements_3 = arr[0:]


print(" Extratced all elements from original array arr using slicing notation [:]  ->", all_elements_1)
print(" Extratced all elements from original array arr using slicing notation [::] ->", all_elements_2)
print(" Extratced all elements from original array arr using slicing notation [0:] ->", all_elements_3)

 Original array: [10 20 30 40 50]
 Extratced all elements from original array arr using slicing notation [:]  -> [10 20 30 40 50]
 Extratced all elements from original array arr using slicing notation [::] -> [10 20 30 40 50]
 Extratced all elements from original array arr using slicing notation [0:] -> [10 20 30 40 50]


In [ ]:
all_elements_3 = arr[0:-1]
print(" Extratced all elements from original array arr using slicing notation [0:-1] ->", all_elements_3)

 Extratced all elements from original array arr using slicing notation [0:-1] -> [10 20 30 40]


### **Select elements with index m through n (exclusive), with step size s**

In [ ]:
import numpy as np

# Create a NumPy array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("Original array:", arr)
# Select elements from index 2 through 7 (exclusive) with a step size of 2
selected_elements = arr[2:7:2]

print("Elememtns from index 2 through 7 (exclusive) with a step size of 2:",selected_elements)


Original array: [ 10  20  30  40  50  60  70  80  90 100]
Elememtns from index 2 through 7 (exclusive) with a step size of 2: [30 50 70]


### **Select all elements from array in reverse order**

In [ ]:
import numpy as np

# Create a NumPy array
arr = np.array([10, 20, 30, 40, 50])
print("Original array:", arr)

# Select all elements in reverse order
reversed_elements = arr[::-1]

print("All elements in reverse order:",reversed_elements)


Original array: [10 20 30 40 50]
All elements in reverse order: [50 40 30 20 10]


### **Slicing in Multidimentional arrays**

### **Slicing in Multidimentional arrays -2d array**

In [ ]:
# Creating 2d ARRAY
import numpy as np
arr_2d = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]
                ])
print("input orginal 2-D array\n",arr_2d)

input orginal 2-D array
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
subarray = arr_2d[0:2, 1:3]
print(" innput original 2-D array\n",arr_2d)
print("Sliced array from 2-D array arr_2d \n",subarray)


 innput original 2-D array
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Sliced array from 2-D array arr_2d 
 [[20 30]
 [50 60]]


In [ ]:
import numpy as np
# Create a 3D array (3x3x3)
arr_3d = np.array([[[10, 20, 30],
                    [40, 50, 60],
                    [70, 80, 90]],

                   [[100, 110, 120],
                    [130, 140, 150],
                    [160, 170, 180]],

                   [[109, 200, 201],
                    [202, 230, 204],
                    [205, 206, 270]]])

# Select a subarray from dimensions 0 to 1 along each dimension
subarray = arr_3d[0:2, 1:3, 0:2]
print(" Input original 3-D array\n",arr_3d)
print("Sliced array from 3-D array arr_3d \n",subarray)

 Input original 3-D array
 [[[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]]

 [[100 110 120]
  [130 140 150]
  [160 170 180]]

 [[109 200 201]
  [202 230 204]
  [205 206 270]]]
Sliced array from 3-D array arr_3d 
 [[[ 40  50]
  [ 70  80]]

 [[130 140]
  [160 170]]]


### **Slicing Rows or Columns: Selecting Specific Rows or Columns**

In [ ]:
# Creating 2d array
import numpy as np
arr_2d = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]
                ])
print("input orginal 2-D array\n",arr_2d)

# slicing the column
column_slice = arr_2d[:, 0]
print("All rows but only the first column (column index 0):\n",column_slice)

# slicing the row
row_slice = arr_2d[2, :]
print("All columns but only the 3rd row (row index 2):\n",row_slice)


input orginal 2-D array
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
All rows but only the first column (column index 0):
 [10 40 70]
All columns but only the 3rd row (row index 2):
 [70 80 90]


In [ ]:
# Creating 2d array
import numpy as np
arr_2d = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90],
                    [100, 110, 120]
                ])
print("input orginal 2-D array\n",arr_2d)

 # Select every 3rd row and every other column
subarray = arr_2d[::3, ::2]
print(" Sliced subarray from 2-D array arr_2d\n",subarray)


input orginal 2-D array
 [[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
 Sliced subarray from 2-D array arr_2d
 [[ 10  30]
 [100 120]]


In [ ]:
# Creating 2d array
import numpy as np
arr_2d = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90],
                    [100, 110, 120]
                ])
print("input orginal 2-D array\n",arr_2d)

# Select the last row and last two columns
subarray = arr_2d[-1, -2:]
print(" Sliced subarray from 2-D array arr_2d\n",subarray)


input orginal 2-D array
 [[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
 Sliced subarray from 2-D array arr_2d
 [110 120]


In [ ]:
# Creating 2d array
import numpy as np
arr_2d = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90],
                    [100, 110, 120]
                ])
print("input orginal 2-D array\n",arr_2d)

# Select the last row and last two columns
subarray = arr_2d[:,1]
print(" Sliced subarray from 2-D array arr_2d\n",subarray)


input orginal 2-D array
 [[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
 Sliced subarray from 2-D array arr_2d
 [ 20  50  80 110]


## **Using Ellipsis (...) for Higher Dimensions**

In [ ]:
import numpy as np

# Create a 3D array (3x3x3)
arr_3d = np.array([
    [[10, 20, 3],
     [40, 50, 60],
     [70, 80, 90]],

    [[100, 101, 120],
     [130, 104, 150],
     [160, 170, 108]],

    [[190, 200, 210],
     [20, 203, 240],
     [205, 206, 207]]
])

# Using ellipsis (...) to select a subarray
# Selects the second column along the last dimension
subarray = arr_3d[..., 1]

print("Original 3D array:\n", arr_3d)
print("\nSliced subarray using ellipsis (...):\n", subarray)

Original 3D array:
 [[[ 10  20   3]
  [ 40  50  60]
  [ 70  80  90]]

 [[100 101 120]
  [130 104 150]
  [160 170 108]]

 [[190 200 210]
  [ 20 203 240]
  [205 206 207]]]

Sliced subarray using ellipsis (...):
 [[ 20  50  80]
 [101 104 170]
 [200 203 206]]


In [ ]:
import numpy as np

# Create a 3D array (3x3x3)
arr_3d = np.array([
    [[10, 20, 3],
     [40, 50, 60],
     [70, 80, 90]],

    [[100, 101, 120],
     [130, 104, 150],
     [160, 170, 108]],

    [[190, 200, 210],
     [20, 203, 240],
     [205, 206, 207]]
])

# Using (:) to select a subarray
# Selects the second column along the last dimension
subarray = arr_3d[:,:, 1]

print("Original 3D array:\n", arr_3d)
print("\nSliced subarray using (:) :\n", subarray)

Original 3D array:
 [[[ 10  20   3]
  [ 40  50  60]
  [ 70  80  90]]

 [[100 101 120]
  [130 104 150]
  [160 170 108]]

 [[190 200 210]
  [ 20 203 240]
  [205 206 207]]]

Sliced subarray using (:) :
 [[ 20  50  80]
 [101 104 170]
 [200 203 206]]
